name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        


    - name: Install dependencies backend
      run: npm install
      working-directory: ./backend

    - name: Install dependencies frontend
      run: npm install
      working-directory: ./frontend

    - name: Install dependencies frontend angular
      run: npm install -g @angular/cli
      working-directory: ./frontend

    - name : Build frontend
      run: ng build
      working-directory: ./frontend

    - name: Run tests
      run: npx cypress run
      working-directory: ./frontend



